### ISSUE TITLE
LanguageTranslation Service Constants

### ISSUE THREAD

**Issue by jpetitto** [watson-developer-cloud/android-sdk#2]
The `LanguageTranslation` service API in the Java SDK does not define any constants for supported languages. For example, right now you have to write:

``` java
service.translate("hello", "en", "es");
```

Rather, having a set of pre-defined constants (an enum most likely) of languages supported by the service would be more helpful:

``` java
service.translate("hello", Language.EN, Language.ES);
```

**Comment by germanattanasio** [comment]
fixed
