### ISSUE TITLE
[text-to-speech] Provide functionality to stop the StreamPlayer

### ISSUE THREAD

**Issue by hendrawd** [watson-developer-cloud/android-sdk#21]
As asked in http://stackoverflow.com/questions/41256985/how-to-stop-streamplayer-of-ibm-watson-text-to-speech

I want to stop StreamPlayer when quitting an Activity where the StreamPlayer play the audio. How i can achieve that with the current sdk?

sdk used
```
compile 'com.ibm.watson.developer_cloud:java-sdk:3.5.3'
compile 'com.ibm.watson.developer_cloud:android-sdk:0.2.1'
```

**Comment by germanattanasio** [comment]
I think this is particular of Android so I will let @blakesteve answer it

**Comment by Hsaylor** [comment]
I believe this functionality should have been added with #26. Can you confirm/deny @blakesteve ?

**Comment by blakesteve** [comment]
Agreed, calling `interrupt` provides the requested functionality. Thanks Harrison, closing
