### ISSUE TITLE
Failed to resolve: com.ibm.watson.developer_cloud:android-sdk:0.4.0

### ISSUE THREAD

**Issue by VidyasagarMSC** [watson-developer-cloud/android-sdk#38]
Error:(40, 13) Failed to resolve: com.ibm.watson.developer_cloud:android-sdk:0.4.0

**Comment by lpatino10** [comment]
Thanks for the heads up. The configuration for Bintray releases seems to be messed up so I'm going to look at that now. In the meantime, you can continue to use version 0.2.3.

**Comment by germanattanasio** [comment]
@VidyasagarMSC we are aware and we are working on a new release.

**Comment by lpatino10** [comment]
@VidyasagarMSC The new release is up now (0.4.2). If you still have any speech-to-text problems, feel free to make a new issue for us to take a look at.

**Comment by brian-chu-twc** [comment]
Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

Look like your library requires 26.0.1 instead of 25.3.1

**Comment by germanattanasio** [comment]
@brian-chu-twc can you explain what you mean by 26.0.1? I'm not an android developer.

**Comment by brianchu** [comment]
I file other ticket, will explain it there. thanks!
