### ISSUE TITLE
Cannot compile with 25.3.1

### ISSUE THREAD

**Issue by brian-chu-twc** [watson-developer-cloud/android-sdk#42]
Compile with 0.4.2, get this error:

Error:(15, 21) No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

Look like the library requires support library version 26.0.1 instead of 25.3.1 is that correct?

**Comment by lpatino10** [comment]
That would be correct. Please try updating your support library dependency and let me know if you have any more issues.
