### ISSUE TITLE
Requesting support for API key authentication for STT & TTS services

### ISSUE THREAD

**Issue by ShreeyaJoshi** [watson-developer-cloud/android-sdk#53]
Hi All,
I created new STT and TTS service in IBM Cloud, and I see fields in Credentials like:-
- apikey
- iam_apikey_description
- iam_apikey_name
- iam_role_crn
- iam_serviceid_crn
- url
but I don't see Username, Password in credentials (as mentioned in documentation of current android-sdk)
Can you let me know the endpoint I should use for connecting to latest services.

**Comment by lpatino10** [comment]
Hey @ShreeyaJoshi. For authentication, refer to the [Java SDK](https://github.com/watson-developer-cloud/java-sdk). Our services have migrated to a new authentication method.

**Comment by ShreeyaJoshi** [comment]
Thank you for quick response @lpatino10, will take a look at it

**Comment by ShreeyaJoshi** [comment]
Hi Logan, We are looking for Android SDK, and above link is for Java SDK, can you guide on how to proceed further with this?

**Comment by lpatino10** [comment]
For authentication I specifically mean [this section](https://github.com/watson-developer-cloud/java-sdk#iam) of the README.

The Android SDK is just a library to be used on top of the Java SDK. The Android SDK adds support for device-specific things like the camera and microphone, but the Java SDK deals with connecting to the Watson services. That repo's README should be useful then in better understanding how to use the services.

For more details on authentication with the new system, you can look [here](https://console.bluemix.net/docs/services/watson/getting-started-iam.html#iam), which is not Java-specific.
