### ISSUE TITLE
Example is not using the latest Watson SDK 

### ISSUE THREAD

**Issue by foward** [watson-developer-cloud/android-sdk#57]
The Example folder is not using the latest Watson SDK, please update it to the new version since there are code which is deprecated. 

Thanks  @lpatino10  @germanattanasio

**Comment by germanattanasio** [comment]
Thanks a lot for filing this issue! Would you like to write a patch for this? We'd be more than happy to walk you through the steps involved.

**Comment by lpatino10** [comment]
I've started updating the example to use the newest version of the Java SDK, but have run into an issue with the Text to Speech output. I've got an issue internally to track the progress and I'll be looking into it more deeply next week.

**Comment by germanattanasio** [comment]
This was fixed in #63
