### ISSUE TITLE
Cannot create variant 'android-lint' after configuration

### ISSUE THREAD

**Issue by priyankjain28** [watson-developer-cloud/android-sdk#58]
Hi Team,
I cannot build my project.
I get this error 
Cannot create variant 'android-lint' after configuration ':library:debugRuntimeElements' has been resolved

**Comment by lpatino10** [comment]
Hi @priyankjain28. Without knowing much about your project, this link seems to be pointing to a very similar problem and solution.

Please take a look at that and let me know if this fixes anything for you.

**Comment by priyankjain28** [comment]
Thanks

**Comment by germanattanasio** [comment]
This issue is fairly old and there hasn't been much activity on it. Closing, but please re-open if it still occurs.
