### ISSUE TITLE
[speech-to-text] Interim results set to true but seeing final results

### ISSUE THREAD

**Issue by VidyasagarMSC** [watson-developer-cloud/android-sdk#64]
I have set the .interimResults(true) for Speech to Text new RecognizeOptions.Builder()
 but still seeing the final results.

### When reporting a bug, please be sure to include the following:

I have used the examples code and set the interimResults to true. But when I check the response I always see this 

```
{
      "result_index": 0,
      "results": [
        {
          "alternatives": [
            {
              "confidence": 0.728,
              "transcript": "hi what should I call you "
            }
          ],
          "final": true
        }
      ]
    }
```

I am using the latest release of the SDK (0.5.0). Am I missing anything here?

Just figured out that the getRecognizeOptions is never setting the interimResults. getRecognizeOptions output

```
 {
      "content-type": "audio/ogg;codec=opus",
      "inactivityTimeout": 2000,
      "model": "en-US_BroadbandModel"
    }
```

**Comment by VidyasagarMSC** [comment]
@l2fprod yep...after digging deep just found out that the main issue is with Java SDK. Created an issue on Java SDK repo - https://github.com/watson-developer-cloud/java-sdk/issues/1005

It still makes sense to have this issue open here. So that the fix from Java SDK can move into SDK.

**Comment by lpatino10** [comment]
Good catch @l2fprod and @VidyasagarMSC. I'll release a patch today and update this and the Java issue when it's released.

**Comment by lpatino10** [comment]
@VidyasagarMSC the fix has been applied in the Java SDK, so this issue can be closed. Thanks to you and @l2fprod for the help 👌
