### ISSUE TITLE
Add instructions on how to use ProGuard to prevent the limitation for jars with > 32000 methods

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/android-sdk#7]
We should add instructions on how to use the `android-sdk` with ProGuard so that users have some information when they want to submit the app to the Google Store.

**Comment by Hsaylor** [comment]
Instructions about Multidex Support and ProGuard have been added to [the wiki](https://github.com/watson-developer-cloud/android-sdk/wiki/Multidex-Support)
