### ISSUE TITLE
Helpp Speaker Labeling is not consistent

### ISSUE THREAD

**Issue by prokulit06** [watson-developer-cloud/android-sdk#72]
When i try in the demo transcribing audio to text is so accurate this is the output in the demo
Speaker 0:
    Hello. 
Speaker 1:
    Hi is this Tina. 
Speaker 0:
    Yes it is who is this. 
this is my output
Speaker 0:
    Hello. 
Speaker 1:
    Hi is this Tina. 
Speaker 0:
    Yes it is this this
this is my set up in recognize
 private RecognizeOptions getRecognizeOptions(InputStream captureStream) {
        return new RecognizeOptions.Builder()
                .audio(captureStream)
                .contentType(HttpMediaType.AUDIO_MP3)
                .model("en-US_NarrowbandModel")
                .interimResults(true)
                .inactivityTimeout(-1)
                .timestamps(true)
                .speakerLabels(true)
                .smartFormatting(true)
                .build();
    }
when i trying to change the model into a en-US_Broadband this the output
Speaker 0:
    Hello. 
Speaker 1:
    Hi is this Tina. Yes it is who is this
The diferrence is the word Yes it is who is this is a different speaker so the expected result will be this
Speaker 0:
    Hello. 
Speaker 1:
    Hi is this Tina. 
Speaker 0:
    Yes it is who is this. 
please help is this bug or there is something error on my code by the way i am using mp3 file not wav file

**Comment by prokulit06** [comment]
please help me

**Comment by prokulit06** [comment]
need help sir

**Comment by lpatino10** [comment]
This is not an issue with the Android SDK. If you're confused about getting the most out of the Speech to Text service, please consult the documentation: https://cloud.ibm.com/docs/services/speech-to-text
