### ISSUE TITLE
update example include of speaker label

### ISSUE THREAD

**Issue by prokulit06** [watson-developer-cloud/android-sdk#74]
Sir please can you provide on example on how to get speaker label just like in the demo very consistent please sir

**Comment by lpatino10** [comment]
@prokulit06 

Issues submitted to this repository should be either _bugs_ found in using the SDK or _reasonable questions_ about support on how to use it. Even in that latter case, they should pertain directly to the SDK itself.

The question you're asking is related to Watson services as a whole and how best to train them. This is information that can be found in the service documentation which I've linked you to before.

I don't mind trying to help people use the SDK, but it is time-consuming and you've submitted 6 issues in the past few weeks which mostly revolve around helping you write your code. This isn't something I have time to spend on.

I'm closing this issue. Please consult the [Watson service documentation](https://cloud.ibm.com/docs/home/alldocs?category=ai) and refrain from creating further issues unless you've found a legitimate problem in the code or are genuinely confused about how to use something after having done a little bit of research.
