### ISSUE TITLE
ERROR: Cannot create variant 'android-aidl' after configuration ':library:debugApiElements' has been resolved

### ISSUE THREAD

**Issue by W-quan** [watson-developer-cloud/android-sdk#78]
reopen [#69](https://github.com/watson-developer-cloud/android-sdk/issues/69).

env:

`com.android.tools.build:gradle:3.4.0`
`com.dicedmelon.gradle:jacoco-android:0.1.4`

`gradle-5.1.1-all.zip`

**Comment by lpatino10** [comment]
@W-quan It seems like it's an error coming from the version of Gradle you're using. You might be able to solve it by downgrading, as it's probably incompatible with a library you're using (which might be this one).

For reference, we're using Gradle version `2.3.3` in this project, so it might be worth giving that one a try.

**Comment by W-quan** [comment]
```
ERROR: No toolchains found in the NDK toolchains folder for ABI with prefix: mips64el-linux-android
This version of the NDK may be incompatible with the Android Gradle plugin version 3.0 or older.
Please use plugin version 3.1 or newer.
```
It's a Infinite loop.   The gradle version `2.3.3` is too old. Can you upgradle it?
