### ISSUE TITLE
Error: INSTALL_FAILED_CONFLICTING_PROVIDER: Can't install because provider name com.ibm.watson.developer_cloud.android.provider  is already used

### ISSUE THREAD

**Issue by aurelN** [watson-developer-cloud/android-sdk#79]
Hello,

The following error appears when I try to install an app using watson on a device which already has another app with watson.

From what I read this could be fixed by changing the SDK manifest instead of
<provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="com.ibm.watson.developer_cloud.android.provider"

to use

<provider
        android:name="android.support.v4.content.FileProvider"
        android:authorities="${applicationId}.com.ibm.watson.developer_cloud.android.provider"

or any other unique authority

**Comment by lpatino10** [comment]
Hey @aurelN, thanks for bringing this up. I can take a look when I get a chance to try that out. In the meantime though, feel free to submit a PR if you would like. I'd be happy to review!
