### ISSUE TITLE
Update the Android-sdk based on the latest changes from the java-sdk

### ISSUE THREAD

**Issue by germanattanasio** [watson-developer-cloud/android-sdk#8]
We released a new java-sdk that doesn't have major changes but I bet there are version numbers in the README or in the examples that we need to update

**Comment by honeynatividad** [comment]
Error:(27, 13) Failed to resolve: com.ibm.watson.developer_cloud:android-sdk:0.1.0

**Comment by Hsaylor** [comment]
@honeynatividad embarrassingly the sdk wasn't uploaded properly. Should be fixed now.

**Comment by honeynatividad** [comment]
Thank you! Anyway I am wandering why en-US_MichaelVoice is not listed?

**Comment by Hsaylor** [comment]
This sdk is simply a set of util tools to help on Android. For the actual Watson services check out the [Java SDK](https://github.com/watson-developer-cloud/java-sdk). Voices can be found in the Voice class.
