### ISSUE TITLE
[speech-to-text] [websocket] Implement Speech to text using Web Socket

### ISSUE THREAD

**Issue by kanika712** [watson-developer-cloud/android-sdk#81]
In the previous "https://github.com/watson-developer-cloud/speech-android-sdk" project we were having WebSocket class. But i did't find such class in this project. I want to achieve speech to text using webSocket .Please help..

**Comment by lpatino10** [comment]
Hey sorry @kanika712, this slipped past my radar.

The way this project works is in tandem with the [Java SDK](https://github.com/watson-developer-cloud/java-sdk), meaning that you should also be including that project in your dependencies. You can see an example of that in the example code [here](https://github.com/watson-developer-cloud/android-sdk/blob/master/example/src/main/java/com/ibm/watson/developer_cloud/android/myapplication/MainActivity.java#L149).
