### ISSUE TITLE
com.ibm.watson.developer_cloud:android-sdk:0.5.1 not found

### ISSUE THREAD

**Issue by monochkov** [watson-developer-cloud/android-sdk#84]
**Details:** org.gradle.api.internal.artifacts.ivyservice.DefaultLenientConfiguration$ArtifactResolveException: Could not resolve all files for configuration ':app:debugImplementationDependenciesMetadata'.
**Caused by:** org.gradle.internal.resolve.ArtifactNotFoundException: Could not find android-sdk.jar (com.ibm.watson.developer_cloud:android-sdk:0.5.1).
**Searched in the following locations:**
    https://jcenter.bintray.com/com/ibm/watson/developer_cloud/android-sdk/0.5.1/android-sdk-0.5.1.jar</i>

P.S. com.ibm.watson.developer_cloud:android-sdk:0.5.0 works fine

**Comment by germanattanasio** [comment]
@lpatino10 what's the problem here? do we use bintray for android-sdk?

**Comment by lpatino10** [comment]
Sorry about that @monochkov, it seems like there was an issue with the last automated release that caused the AAR file not to be uploaded.

I just uploaded it and was able to pull down the library successfully. I'm going to go ahead and close this but feel free to re-open if you're still having trouble.

Thanks again for the heads-up!
