### ISSUE TITLE
README.md link to AAR broken

### ISSUE THREAD

**Issue by smccants** [watson-developer-cloud/android-sdk#85]
The README.md file contains a link for downloading a binary AAR, but the link returns a 404.  The link in the README.md is currently:

https://github.com/watson-developer-cloud/android-sdk/releases/download/v0.5.1/library-release.aar

Please either fix the link or remove it if you no longer provide an AAR file.

**Comment by smccants** [comment]
This page shows an aar built for 0.5.0 and earlier, but not 0.5.1:

https://github.com/watson-developer-cloud/android-sdk/releases/

**Comment by smccants** [comment]
If you are no longer providing an AAR file, can you provide build instructions?  It would be appreciated.

**Comment by germanattanasio** [comment]
I think this is a problem we are looking as part of #84

**Comment by smccants** [comment]
@germanattanasio Could be.  #84 doesn't really make any sense to me, but that is likely because I don't know enough about the topic.

**Comment by lpatino10** [comment]
Sorry about that @smccants. There was an issue with the last release not publishing the artifacts and I didn't catch it. They should be up in the release now.

**Comment by smccants** [comment]
@lpatino10 I can verify that the link is working now and the artifacts are listed correctly on the release page.  Thanks for the quick fix!
